### ISSUE TITLE
Algorithm to find all the factors of a given number

### ISSUE THREAD

**Issue by Bhushan8177** [Princeton21/Hacktoberfest_DSA_2021#177]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Create a folder in the [math](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/math) directory and add the implementation of your code.

You can implement this algorithm in any language of your preference.

While requesting to be assigned, kindly specify the language in which you will implement
the algorithm.

And while sending your pull request don't forget to mention on which issue you have worked with (#issue_number)

**Comment by momosetti** [comment]
Hi @Princeton21, I worked on this issue. Here's my PR #368.
