### ISSUE TITLE
Find n’th Fibonacci number

### ISSUE THREAD

**Issue by Mjcev** [Princeton21/Hacktoberfest_DSA_2021#288]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

 Find n’th Fibonacci number in /Code/math/ section

**Comment by Princeton21** [comment]
Sure @Aaryan2808

**Comment by Aaryan2808** [comment]
> Sure @Aaryan2808

@Princeton21 i've create the issue for the same, please assign it to me

**Comment by momosetti** [comment]
Hi @Princeton21, I worked on this issue via the #373 PR.
