### ISSUE TITLE
Add a game project

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Hacktoberfest_DSA_2021#29]
Everyone has implemented at least one short game in their life.
Your task is to add a project of any game of your choice
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

There are a few folders of common games created in the [game_projects](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/game_projects) directory.

If you want to implement a new game, kindly create a folder in the above directory.

Submit a program of the game of your choice in the respective game folder.

You can implement this program in any language you prefer.

While requesting to be assigned, kindly specify the game you will be working on and the language in which you will implement the program.

**Comment by Kevinjadia** [comment]
@Princeton21 I've added a movie name guessing game issue? Can you assign me that issue?

**Comment by Kevinjadia** [comment]
@Princeton21  Can you assign me the issue #337 to create a Concentration game?

**Comment by Kevinjadia** [comment]
@Princeton21 Please assign me both the above two issues, implementation for both is almost ready!

**Comment by Princeton21** [comment]
sure

**Comment by Mjcev** [comment]
Hi @Princeton21 I create a tower of Hanoi game in Python
