### ISSUE TITLE
Want to add Maximum Sum Subarray Problem (Kadane’s Algorithm)

### ISSUE THREAD

**Issue by ajjju1** [Princeton21/Hacktoberfest_DSA_2021#327]
**This is Kadane’s Algorithm:**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Given an integer array, find a contiguous subarray within it that has the largest sum

We can easily solve this problem in linear time using Kadane's algorithm. The idea is to maintain am maximum(positive-sum) subarray "ending" at each index of the given array. This subarray is either empty( in which case its sum is zero ) or consist of one element than the maximum subarray ending at previous index.

**Comment by ajjju1** [comment]
can you please add hacktoberfest label on this issue

**Comment by Princeton21** [comment]
Sure
