### ISSUE TITLE
Movie name guessing game

### ISSUE THREAD

**Issue by Kevinjadia** [Princeton21/Hacktoberfest_DSA_2021#335]
**Details:**

Make 2 player movie guessing game with the following rules using Python:
1. Basically both the player needs to guess the characters of the movie name and if that character is present in the movie name then it'll be revealed! if the whole movie name is revealed by guesses then that player wins
2. Both the player have 3 chances to play the game whoever wins maximum times will be the winner
3. Scores of both players will be calculated at the end of each chance.
4. Both the player will have a maximum of 5 chances for the wrong guesses! if the player guesses the wrong characters 5 times he'll lose!

**Comment by Srivastava57Harsh** [comment]
@Kevinjadia  please assign this to me
