### ISSUE TITLE
Greatest Common Divisor in Java

### ISSUE THREAD

**Issue by Aaryan2808** [Princeton21/Hacktoberfest_DSA_2021#364]
Here I'll be Creating a program which helps in finding the GCD i.e greatest common divisor of 2 numbers

**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**
Here I'll be Creating a program which helps in finding the GCD i.e greatest common divisor of 2 numbers using java programming language, using simple conditional loop statements

**Comment by Aaryan2808** [comment]
Hey @Princeton21 please assign me this issue, i want to work on this in java

**Comment by Princeton21** [comment]
Sure be quick.

**Comment by Aaryan2808** [comment]
> Sure be quick.

yes, but you haven't yet assigned me this issue
