### ISSUE TITLE
Finding Kth largest element from given array using c++

### ISSUE THREAD

**Issue by Kevinjadia** [Princeton21/Hacktoberfest_DSA_2021#377]
Given the size of array n and array of distinct elements. Find the kth largest element in it.

Example 1:

Input: 
n = 5
K=2
A[] = {8,4,2,1,5}

Output: 5

Example 2:

Input:
n= 2 
k=3
A[] = {1,2}

Output: Can't find kth largest element as k>n

**Comment by Kevinjadia** [comment]
@Princeton21 Can you assign me this issue of DSA?

**Comment by Princeton21** [comment]
Try to make the code to find the nth largest element.
