### ISSUE TITLE
Add your solutions to a competitive programming problem

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Hacktoberfest_DSA_2021#9]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Add your solution to the respective location (be it hackerrank ,codechef or leetcode) in the
[online_problems](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/online_problems) folder

**Comment by akshat19231** [comment]
@Princeton21 I have added another problem, kindly merge the PR! (Hacktoberfest is ending :( )
